#!/usr/bin/env perl

use Mojo::DOM;
use Path::Class qw/file/;
use YAML qw/Dump/;
use Encode;
use lib './lib';
use nca3parse;
binmode STDOUT, ':utf8';
binmode STDERR, ':utf8';

use v5.14;

sub usage {
    say "usage : $0 <file.html>";
    say "example : ";
    say "$0 html/ch02/ch02.html > findings/ch02.yaml";
    exit;
}

my $file = shift or usage();

my @dump;

$file = decode('UTF-8',scalar file($file)->slurp);
#$file =~ s[<b>][]ig;
#$file =~ s[</b>][]gi;

my $dom = Mojo::DOM->new($file);

my @nodes  = map { $_ } $dom->find('p')->each;
my @ps = map { $_->all_text } @nodes;

my @dump;

my %seen;

my $process;
for my $i (0..$#nodes) {
    my $r;
    my $txt = $ps[$i];
    if (!$process and
        ($txt =~ s/^(Key Message )?Process for developing key messages://i or
        $txt =~ s/key message process://i
        )) {
        $process = $txt;
        for my $lookahead (1..5) {
            last if $ps[$i + $lookahead] =~ /key message \#\d/i;
            $process .= "\n";
            $process .= $ps[$i + $lookahead];
        }
        next;
    }
    $txt =~ m[^key message #(\d+)(/\d+| traceable account)]mi or next;
    $r->{ordinal} = $1;
    next if $seen{$1}++;
    my $which = 'statement';
    for my $lookahead (1..20) {
        $txt = _munge($txt);
        my $txt = $ps[$i + $lookahead] or next;
        if ($txt =~ /Description of evidence base/i) {
            $which = 'evidence';
            next;
        }
        if ($txt =~ /New information and remaining uncertainties/i) {
            $which = 'uncertainties';
            next;
        }
        if ($txt =~ /Assessment\s+of\s+confidence\s+based\s+on\s+evidence/i) {
            $which = 'confidence';
            next;
        }
        last if $txt =~ /CONFIDENCE LEVEL/;
        last if $txt =~ /References/;
        last if $txt =~ /Key message #/;
        $r->{$which} .= "\n" if $r->{$which};
        $r->{$which} .= $txt;
    }
    push @dump, $r;
}

$_->{process} = $process for @dump;

say Dump(\@dump);


#------------------------------
sub _munge {
    my $str = shift or return;
    $str =~ s/R ising/Rising/;
    return $str;
}

__END__

Sample output file produced :

---
- confidence: |-
    Observed trends have been demonstrated by a broad range of methods over the past 20+ years based on best available data; projected precipitation and river-flow responses to greenhouse gas increases are robust across large majorities of available climate (and hydrologic) models from scientific teams around the world.
    Confidence is therefore judged to be high that annual precipitation and river-flow increases are observed now in the Midwest and the Northeast regions.
    Confidence is high that very heavy precipitation events have increased nationally and are projected to increase in all regions.
    Confidence is high that the length of dry spells is projected to increase in most areas, especially the southern and northwestern portions of the contiguous United States.
  evidence: |-
    The key message and supporting chapter text summarizes extensive evidence documented in the inter-agency prepared foundational document,<tbib>50d47cc1-5a16-4f5c-bb08-bf6f475a5bb8</tbib> Ch. 2: Our Changing Climate, Ch. 20: Southwest, other technical input reports,<tbib>0ebef171-4903-4aa6-b436-2936da69f84e</tbib> and over 500 technical inputs on a wide range of topics that were received as part of the Federal Register Notice solicitation for public input.
    Numerous peer-reviewed publications describe precipitation trends (Ch. 2: Our Changing Climate)<tbib>8c8612b7-b9b5-427e-a1d4-c49de8346733</tbib><sup>,</sup><tbib>c0da4df5-149d-4ef9-a1ac-96db76da12af</tbib><sup>,</sup><tbib>cc98a8b5-74b3-4df2-8961-7799768da2ed</tbib><sup>,</sup><tbib>d1069afd-d9c4-4cc1-bd29-c50f637502bd</tbib><sup>,</sup><tbib>c3ef1f99-a398-45f5-ab9b-9495402070af</tbib><sup>,</sup><tbib>7259bc2b-d0aa-460b-b37a-79a11a386e00</tbib> and river-flow trends.<tbib>4a6f7d87-75aa-49eb-81a7-0b078c6fc126</tbib><sup>,</sup><tbib>542ee728-8d13-448a-a83d-e90d9dbd3dcf</tbib><sup>,</sup><tbib>b8724db5-9d7b-458e-a570-e8c386ccc4f6</tbib><sup>,</sup><tbib>67b69161-5101-418a-a6c9-1b6a80773305</tbib> As discussed in Chapter 2, the majority of projections available from climate models (for example, <tbib>73bd27a4-2d08-49c7-81ee-dbb12667e6df</tbib><sup>,</sup><tbib>d85a45c6-1da6-41f1-81d6-e855acfb1fe3</tbib>) indicate small projected changes in total average annual precipitation in many areas, while heavy precipitation<tbib>5d909426-fab3-4dc8-af56-e5fe414ca97a</tbib><sup>,</sup><tbib>8e50e700-be4b-49eb-970a-93a592221589</tbib> and the length of dry spells are projected to increase across the entire country. Projected precipitation responses (such as changing extremes) to increasing greenhouse gases are robust in a wide variety of models and depictions of climate.
    The broad observed trends of precipitation and river-flow increases have been identified by many long-term National Weather Service (NWS)/National Climatic Data Center (NCDC) weather monitoring networks, USGS streamflow monitoring networks, and analyses of records therefrom (Ch. 2: Our Changing Climate <tbib>7259bc2b-d0aa-460b-b37a-79a11a386e00</tbib><sup>,</sup><tbib>de270af6-30e7-403e-8352-6d5809c346c7</tbib><sup>,</sup><tbib>9fc00216-c35c-4958-b5f4-93517d667fd0</tbib>). Ensembles of climate models<tbib>73bd27a4-2d08-49c7-81ee-dbb12667e6df</tbib><sup>,</sup><tbib>c52f2539-9c5e-4ead-b8b7-f1884c5d662e</tbib>(see also Ch. 2: Our Changing Climate, Ch. 20: Southwest) are the basis for the reported projections.
  ordinal: 1
  process: ' The chapter author team engaged in multiple technical discussions via teleconferences from March – June 2012. These discussions followed a thorough review of the literature, which included an inter-agency prepared foundational document,<tbib>50d47cc1-5a16-4f5c-bb08-bf6f475a5bb8</tbib> over 500 technical inputs provided by the public, as well as other published literature. The author team met in Seattle, Washington, in May, 2012 for expert deliberation of draft key messages by the authors wherein each message was defended before the entire author team before this key message was selected for inclusion in the Chapter. These discussions were supported by targeted consultation with additional experts by the lead author of each message, and they were based on criteria that help define “key vulnerabilities.” Key messages were further refined following input from the NCADAC report integration team and authors of Ch. 2: Our Changing Climate.'
  statement: 'Annual precipitation and river-flow increases are observed now in the Midwest and the Northeast regions. Very heavy precipitation events have increased nationally and are projected to increase in all regions. The length of dry spells is projected to increase in most areas, especially the southern and northwestern portions of the contiguous United States.'
  uncertainties: |-
    Important new evidence (cited above) confirmed many of the findings from the prior National Climate Assessment.<tbib>e251f590-177e-4ba6-8ed1-6f68b5e54c8a</tbib>
    Observed trends: Precipitation trends are generally embedded amidst large year-to-year natural variations and thus trends may be difficult to detect, may differ from site to site, and may be reflections of multi-decadal variations rather than external (human) forcings. Consequently, careful analyses of longest-term records from many stations across the country and addressing multiple potential explanations are required and are cornerstones of the evidentiary studies described above.
    Efforts are underway to continually improve the stability, placement, and numbers of weather observations needed to document trends; scientists also regularly search for other previously unanalyzed data sources for use in testing these findings.
    Projected trends: The complexity of physical processes that result in precipitation and runoff reduces abilities to represent or predict them as accurately as would be desired and with the spatial and temporal resolution required for many applications; however, as noted, the trends at the scale depicted in this message are very robust among a wide variety of climate models and projections, which lends confidence that the projections are appropriate lessons from current climate (and streamflow) models. Nonetheless, other influences not included in the climate change projections might influence future patterns of precipitation and runoff, including changes in land cover, water use (by humans and vegetation), and streamflow management.
    Climate models used to make projections of future trends are continually increasing in number, resolution, and in the number of additional external and internal influences that might be confounding current projections. For example, much more of all three of these directions for improvement are already evident in projection archives for the next IPCC assessment.
- confidence: |-
    Given the evidence base and remaining uncertainties:
    Confidence is judged to be medium-high that short-term (seasonal or shorter) droughts are expected to intensify in most U.S. regions. Confidence is high that longer-term droughts are expected to intensify in large areas of the Southwest, southern Great Plains, and Southeast.
  evidence: |-
    The key message and supporting chapter text summarizes extensive evidence documented in the inter-agency prepared foundational document,<tbib>50d47cc1-5a16-4f5c-bb08-bf6f475a5bb8</tbib> Ch. 16: Northeast, Ch 17: Southeast, Ch. 2: Our Changing Climate, Ch. 18: Midwest, Ch. 19: Great Plains, Ch. 20: Southwest, Ch. 21: Northwest, Ch. 23: Hawai ‘ i and Pacific Islands, and over 500 technical inputs on a wide range of topics that were received as part of the Federal Register Notice solicitation for public input.
    Projected drought trends derive directly from climate models in some studies (for ex ample, <tbib>c3ef1f99-a398-45f5-ab9b-9495402070af</tbib><sup>,</sup><tbib>948ffa58-24f3-4129-90c3-8d49f3172f74</tbib><sup>,</sup><tbib>a75e4d22-485a-43c8-9093-931eea728bce</tbib><sup>,</sup><tbib>f6476787-f701-448c-a285-7b763c51df2e</tbib>), from hy drologic models responding to projected climate trends in others (for example, <tbib>ad8c9969-ccf5-47ef-8f13-2e3c53fb3697</tbib><sup>,</sup><tbib>f11e90fb-b100-4487-8bac-1a076166d623</tbib>), from considerations of the interactions between precipitation deficits and either warmer or cooler temperatures in historical (observed) droughts,<tbib>f11e90fb-b100-4487-8bac-1a076166d623</tbib> and from combinations of these approaches (for example, <tbib>8e2fc237-9d2b-4788-bd3e-e8654eaaecc2</tbib>) in still other studies.
  ordinal: 2
  process: ' The chapter author team engaged in multiple technical discussions via teleconferences from March – June 2012. These discussions followed a thorough review of the literature, which included an inter-agency prepared foundational document,<tbib>50d47cc1-5a16-4f5c-bb08-bf6f475a5bb8</tbib> over 500 technical inputs provided by the public, as well as other published literature. The author team met in Seattle, Washington, in May, 2012 for expert deliberation of draft key messages by the authors wherein each message was defended before the entire author team before this key message was selected for inclusion in the Chapter. These discussions were supported by targeted consultation with additional experts by the lead author of each message, and they were based on criteria that help define “key vulnerabilities.” Key messages were further refined following input from the NCADAC report integration team and authors of Ch. 2: Our Changing Climate.'
  statement: 'Short-term (seasonal or shorter) droughts are expected to intensify in most U.S. regions. Longer-term droughts are expected to intensify in large areas of the Southwest, southern Great Plains, and Southeast.'
  uncertainties: |-
    Important new evidence (cited above) confirmed many of the findings from the prior National Climate Assessment. <tbib>e251f590-177e-4ba6-8ed1-6f68b5e54c8a</tbib>
    Warmer temperatures are robustly projected by essentially all climate models, with what are generally expected to be directly attendant increases in the potentials for greater evapotranspiration, or ET (although it is possible that current estimates of future ET are overly influenced by temperatures at the expense of other climate variables, like wind speed, humidity, net surface radiation, and soil moisture that might change in ways that could partly ameliorate rising ET demands). As a consequence, there is a widespread expectation that more water from precipitation will be evaporated or transpired in the warmer future, so that except in regions where precipitation increases more than ET increases, less overall water will remain on the landscape and droughts will intensify and become more common. Another widespread expectation is that precipitation variability will increase, which may result in larger swings in moisture availability, with swings towards the deficit side resulting in increased frequencies and intensities of drought conditions on seasonal time scales to times scales of multiple decades. An important remaining uncertainty, discussed in the supporting text for Key Message #1, is the extent to which the types of models used to project future droughts may be influencing results with a notable recent tendency for studies with more complete, more resolved land-surface models, as well as climate models, to yield more moderate projected changes.
    Other uncertainties derive from the possibility that changes in other variables or influences of CO 2 -fertilization and/or land cover change may also partly ameliorate drought intensification. Furthermore in many parts of the country, El Ni ñ o-Southern Oscillation (and other oceanic) influences on droughts and floods are large, and can overwhelm climate change effects during the next few decades. At present, however, the future of these oceanic climate influences remains uncertain.
- confidence: 'Future changes in flood frequencies and intensities will depend on a complex combination of local to regional climatic influences, and the details of complex surface-hydrologic conditions in each catchment (for example, topography, land cover, and upstream management). Consequently, flood frequency changes may be neither simple nor regionally homogeneous, and basin by basin projections may need to be developed. Early results now appearing in the literature have most often projected intensifications of flood regimes, in large part as responses to projections of more intense storms and increasingly rainy (rather than snowy) storms in previously snow-dominated settings. Confidence in current estimates of future changes in flood frequencies and intensities is overall judged to be low.'
  evidence: |-
    The key message and supporting chapter text summarizes extensive evidence documented in the inter-agency prepared foundational document, <tbib>50d47cc1-5a16-4f5c-bb08-bf6f475a5bb8</tbib> Ch. 16: Northeast, Ch 17: Southeast, Ch. 2: Our Changing Climate, Ch. 18: Midwest, Ch. 19: Great Plains, Ch. 20: Southwest, Ch. 21: Northwest, Ch. 23: Hawai ‘ i and Pacific Islands, and over 500 technical inputs on a wide range of topics that were received as part of the Federal Register Notice solicitation for public input.
    The principal observational bases for the key message are careful national-scale flood-trend analyses <tbib>a7f8dbf5-3ec8-4ee1-8740-014006b72bfd</tbib> based on annual peak-flow records from a selection of 200 USGS streamflow gaging stations measuring flows from catchments that are minimally influenced by upstream water uses, diversions, impoundments, or land-use changes with more than 85 years of records, and analyses of two other subsets of USGS gages with long records (including gages both impacted by human activities and less so), including one analysis of 50 gages nationwide <tbib>fcd12450-81ff-4322-8a50-09c0662512eb</tbib> and a second analysis of 572 gages in the eastern U.S.<tbib>a639de52-b0d2-4580-a27c-5039d036d210</tbib>. There is some correspondence among regions with significant changes in annual precipitation (Ch. 2: Our Changing Climate) and soil moisture (Figures 3.2 and 3.3), and annual flood magnitudes (Figure 3.5).<tbib>a7f8dbf5-3ec8-4ee1-8740-014006b72bfd</tbib>
    Projections of future flood-frequency changes result from detailed hydrologic models (for example, <tbib>227f0b59-69f2-47ab-8359-29e4fc383e11</tbib><sup>,</sup><tbib>ffaab9ac-cd7b-47d2-a7df-174dbc479bbb</tbib><sup>,</sup><tbib>37288764-91af-4c74-a5f2-fdf7f088c918</tbib>) of rivers that simulate responses to projected precipitation and temperature changes from climate models; such simulations have only recently begun to emerge in the peer-reviewed literature.
  ordinal: 3
  process: ' The chapter author team engaged in multiple technical discussions via teleconferences from March – June 2012. These discussions followed a thorough review of the literature, which included an inter-agency prepared foundational document,<tbib>50d47cc1-5a16-4f5c-bb08-bf6f475a5bb8</tbib> over 500 technical inputs provided by the public, as well as other published literature. The author team met in Seattle, Washington, in May, 2012 for expert deliberation of draft key messages by the authors wherein each message was defended before the entire author team before this key message was selected for inclusion in the Chapter. These discussions were supported by targeted consultation with additional experts by the lead author of each message, and they were based on criteria that help define “key vulnerabilities.” Key messages were further refined following input from the NCADAC report integration team and authors of Ch. 2: Our Changing Climate.'
  statement: 'Flooding may intensify in many U.S. regions, even in areas where total precipitation is projected to decline.'
  uncertainties: |-
    Important new evidence (cited above) confirmed many of the findings from the prior National Climate Assessment. <tbib>e251f590-177e-4ba6-8ed1-6f68b5e54c8a</tbib>
    Large uncertainties remain in efforts to detect flood-statistic changes attributable to climate change, because a wide range of local factors (such as dams, land-use changes, river channelization) also affect flood regimes and can mask, or proxy for, climate change induced alterations. Furthermore, it is especially difficult to detect any kinds of trends in what are, by definition, rare and extreme events. Finally, the response of floods to climate changes are expected to be fairly idiosyncratic from basin to basin, because of the strong influences of within-storm variations and local, basin-scale topographic, soil and vegetation, and river network characteristics that influence the size and extent of flooding associated with any given storm or season <tbib>7ef83121-d51c-4bc5-b499-e00733fae338</tbib><sup>,</sup><tbib>3fec0e7f-bcdd-42a3-bf79-635bd6adb609</tbib><sup>,</sup><tbib>fcd12450-81ff-4322-8a50-09c0662512eb</tbib><sup>,</sup><tbib>a639de52-b0d2-4580-a27c-5039d036d210</tbib>.
    Large uncertainties still exist as to how well climate models can represent and project future extremes of precipitation. This has – until recently – limited attempts to make specific projections of future flood frequencies by using climate model outputs directly or as direct inputs to hydrologic models. However, precipitation extremes are expected to intensify as the atmosphere warms, and many floods result from larger portions of catchment areas receiving rain as snowlines recede upward. As rain runs off more quickly than snowfall this results in increased flood potential; furthermore, occasional rain-on-snow events exacerbates this effect. This trend is broadly expected to increase in frequency under general warming trends, particularly in mountainous catchments <tbib>73760c11-7b97-4876-a24f-8fb54b01bca9</tbib><sup>,</sup><tbib>fb52dd18-06f2-4774-9262-b00501ff730d</tbib><sup>,</sup><tbib>9417de56-6893-4102-86b7-ad7da4e68b8e</tbib><sup>,</sup><tbib>59b1ce0d-27ed-4224-835a-666a4006d9e8</tbib><sup>,</sup><tbib>7dc6aae5-efaa-489a-807e-8b92e7bcd546</tbib>. Rising sea levels and projected increase in hurricane-associated storm intensity and rainfall rates provide first-principles bases for expecting intensified flood regimes in coastal settings (see Ch. 2: Our Changing Climate ).
- confidence: 'Given the evidence base and remaining uncertainties, confidence is judged to be high that climate change is expected to affect water demand, groundwater withdrawals, and aquifer recharge, reducing groundwater availability in some areas.'
  evidence: |-
    The key message and supporting chapter text summarizes extensive evidence documented in the inter-agency prepared foundational document,<tbib>50d47cc1-5a16-4f5c-bb08-bf6f475a5bb8</tbib> regional chapters of the NCA, and over 500 technical inputs on a wide range of topics that were received as part of the Federal Register Notice solicitation for public input.
    Several recent studies <tbib>1cbe9adb-5060-40dd-b9de-bcc33620cac6</tbib><sup>,</sup><tbib>eabfc538-91ce-4130-9040-d595dc61b92e</tbib><sup>,</sup><tbib>c87bb268-f370-4025-bb46-b4b7c4904ad6</tbib><sup>,</sup><tbib>1e0dbb05-1eb4-4fa9-90a1-100aae9a9354</tbib><sup>,</sup><tbib>d03c7a83-4f19-49d6-92a1-1274791d3151</tbib><sup>,</sup><tbib>d56699d4-19fa-4fd6-bb31-f86c26271029</tbib> have evaluated the potential impacts of changes in groundwater use and recharge under scenarios including climate change, and generally they have illustrated the common-sense conclusion that changes in pumpage can have immediate and significant effects in the nation’s aquifers. This has certainly been the historical experience in most aquifers that have seen significant development; pumpage variations usually tend to yield more immediate and often larger changes on many aquifers than do historical climate variations on time scales from years to decades. Meanwhile, for aquifers in the Southwest, there is a growing literature of geochemical studies that fingerprint various properties of groundwater and that are demonstrating that most western groundwater derives preferentially from snowmelt, rather than rainfall or other sources;<tbib>f9880a6c-7860-448e-96d6-b335ac402583</tbib><sup>,</sup><tbib>9179dcd8-6465-46e1-98d7-65d7e0ea8313</tbib><sup>,</sup><tbib>eabfc538-91ce-4130-9040-d595dc61b92e</tbib><sup>,</sup><tbib>0bca150c-d4da-4e20-ac41-e26cf9ed8195</tbib>. This finding suggests that much western recharge may be at risk of changes and disruptions from projected losses of snowpack, but as yet provides relatively little indication whether the net effects will be recharge declines, increases, or simply spatial redistribution.
  ordinal: 4
  process: ' The chapter author team engaged in multiple technical discussions via teleconferences from March – June 2012. These discussions followed a thorough review of the literature, which included an inter-agency prepared foundational document,<tbib>50d47cc1-5a16-4f5c-bb08-bf6f475a5bb8</tbib> over 500 technical inputs provided by the public, as well as other published literature. The author team met in Seattle, Washington, in May, 2012 for expert deliberation of draft key messages by the authors wherein each message was defended before the entire author team before this key message was selected for inclusion in the Chapter. These discussions were supported by targeted consultation with additional experts by the lead author of each message, and they were based on criteria that help define “key vulnerabilities.” Key messages were further refined following input from the NCADAC report integration team and authors of Ch. 2: Our Changing Climate.'
  statement: 'Climate change is expected to affect water demand, groundwater withdrawals, and aquifer recharge, reducing groundwater availability in some areas.'
  uncertainties: 'The precise responses of groundwater storage and flow to climate change are not well understood, but recent and ongoing studies provide insights on underlying mechanisms.<tbib>1cbe9adb-5060-40dd-b9de-bcc33620cac6</tbib><sup>,</sup><tbib>eabfc538-91ce-4130-9040-d595dc61b92e</tbib><sup>,</sup><tbib>c87bb268-f370-4025-bb46-b4b7c4904ad6</tbib> The observations and modeling evidence to make projections of future responses of groundwater recharge and discharge to climate change are thus far very limited, primarily because of limitations in data availability and in the models themselves. New forms and networks of observations and new modeling approaches and tools are needed to provide projections of the likely influences of climate changes on groundwater recharge and discharge. Despite the uncertainties about the specifics of climate change impacts on groundwater, impacts of reduced groundwater supply and quality would likely be detrimental to the nation.'
- confidence: 'Confidence is high that sea level rise, storms and storm surges, and changes in surface and groundwater use patterns are expected to compromise the sustainability of coastal freshwater aquifers and wetlands.'
  evidence: 'This message has a strong theoretical and observational basis, including considerable historical experience with seawater intrusion into many of the nation’s coastal aquifers and wetlands under the influence of heavy pumpage, some experience with the influences of droughts and storms on seawater intrusion, and experience with seepage of seawater into shallow coastal aquifers under storm and storm surges conditions that lead to coastal inundations with seawater. The likely influences of sea level rise on seawater intrusion into coastal (and island) aquifers and wetlands are somewhat less certain, as discussed below, although it is projected that sea level rise may increase opportunities for saltwater intrusion (see Ch. 25: Coasts).'
  ordinal: 5
  process: ' The chapter author team engaged in multiple technical discussions via teleconferences from March – June 2012. These discussions followed a thorough review of the literature, which included an inter-agency prepared foundational document,<tbib>50d47cc1-5a16-4f5c-bb08-bf6f475a5bb8</tbib> over 500 technical inputs provided by the public, as well as other published literature. The author team met in Seattle, Washington, in May, 2012 for expert deliberation of draft key messages by the authors wherein each message was defended before the entire author team before this key message was selected for inclusion in the Chapter. These discussions were supported by targeted consultation with additional experts by the lead author of each message, and they were based on criteria that help define “key vulnerabilities.” Key messages were further refined following input from the NCADAC report integration team and authors of Ch. 2: Our Changing Climate.'
  statement: 'Sea level rise, storms and storm surges, and changes in surface and groundwater use patterns are expected to compromise the sustainability of coastal freshwater aquifers and wetlands.'
  uncertainties: 'There are few published studies describing the kinds of groundwater quality and flow modeling that are necessary to assess the real-world potentials for sea level rise to affect seawater intrusion <tbib>0cd85833-93ce-41ba-9e43-eb328acacf81</tbib>. Studies in the literature and historical experience demonstrate the detrimental impacts of alterations to the water budgets of the freshwater lenses in coastal aquifers and wetlands around the world (most often by groundwater development), but few evaluate the impacts of sea level rise alone. More studies with real-world aquifer geometries and development regimes are needed to reduce the current uncertainty of the potential interactions of sea level rise and seawater intrusion.'
- confidence: 'Given the evidence base, confidence is medium that increasing air and water temperatures, more intense precipitation and runoff, and intensifying droughts can decrease river and lake water quality in many ways, including increases in sediment, nitrogen, and pollutant loads.'
  evidence: |-
    The key message and supporting chapter text summarizes extensive evidence documented in the inter-agency prepared foundational document,<tbib>50d47cc1-5a16-4f5c-bb08-bf6f475a5bb8</tbib> Ch. 8: Ecosystems, Ch. 15: Biogeochemical Cycles, and over 500 technical inputs on a wide range of topics that were reviewed as part of the Federal Register Notice solicitation for public input.
    Thermal stratification of deep lakes and reservoirs has been observed to increase with increased air and water temperatures,<tbib>50d47cc1-5a16-4f5c-bb08-bf6f475a5bb8</tbib><sup>,</sup><tbib>16e73b9a-8381-4a89-9abd-78f85c401ce0</tbib><sup>,</sup><tbib>96ede898-cecb-42aa-9cc5-f34a27ff45f8</tbib><sup>,</sup><tbib>1cf676c9-b700-4e28-8bf0-87f7613a9f56</tbib> and may be eliminated in shallow lakes. Increased stratification reduces mixing, resulting in reduced oxygen in bottom waters. Deeper set-up of vertical thermal stratification in lakes and reservoirs may reduce or eliminate a bottom cold water zone; this coupled with lower oxygen concentration results in a degraded aquatic ecosystem.
    Major precipitation events and resultant water flows increase watershed pollutant scour and thus increase pollutant loads <tbib>ff7bc276-83ee-4d2b-a388-5409d7da855f</tbib><sup>,</sup><tbib>ff8a2e57-a49d-4e8e-90b1-c09e73b014fe</tbib>. Fluxes of mineral weathering products (for example, calcium, magnesium, sodium, and silicon) have also been shown to increase in response to higher discharge.<tbib>71d72e86-c742-45ff-bb85-2387af876e0f</tbib> In the Mississippi drainage basin, increased precipitation has resulted in increased nitrogen loads contributing to hypoxia in the Gulf of Mexico.<tbib>2def4038-abbc-43aa-b816-c8b195e2cf5b</tbib><sup>,</sup><tbib>f68f6208-6991-4325-8854-881c76072096</tbib> Models predict and observations confirm that continued warming will have increasingly negative effects on lake water quality and ecosystem health.<tbib>16e73b9a-8381-4a89-9abd-78f85c401ce0</tbib>
    Future re-mobilization of sediment stored in large river basins will be influenced by changes in flood frequencies and magnitudes, as well as on vegetation changes in the context of climate and other anthropogenic factors.<tbib>d36aa341-c01e-4f30-91fb-32c520f6c4c6</tbib> Model projections suggest that changes in sediment delivery will vary regionally and by land-use type, but on average could increase by 25% to 55%.<tbib>b126b36f-e46e-422f-9467-fac4965635d9</tbib>
  ordinal: 6
  process: ' The chapter author team engaged in multiple technical discussions via teleconferences from March – June 2012. These discussions followed a thorough review of the literature, which included an inter-agency prepared foundational document,<tbib>50d47cc1-5a16-4f5c-bb08-bf6f475a5bb8</tbib> over 500 technical inputs provided by the public, as well as other published literature. The author team met in Seattle, Washington, in May, 2012 for expert deliberation of draft key messages by the authors wherein each message was defended before the entire author team before this key message was selected for inclusion in the Chapter. These discussions were supported by targeted consultation with additional experts by the lead author of each message, and they were based on criteria that help define “key vulnerabilities.” Key messages were further refined following input from the NCADAC report integration team and authors of Ch. 2: Our Changing Climate.'
  statement: 'Increasing air and water temperatures, more intense precipitation and runoff, and intensifying droughts can decrease river and lake water quality in many ways, including increases in sediment, nitrogen, and other pollutant loads.'
  uncertainties: |-
    It is unclear whether increasing floods and droughts cancel each other out with respect to long-term pollutant loads.
    It is also uncertain whether the absolute temperature differential with depth will remain constant, even with overall lake and reservoir water temperature increases. Further, it is uncertain if greater mixing with depth will eliminate thermal stratification in shallow, previously stratified lakes. Although recent studies of Lake Tahoe provide an example of longer stratification seasons, <tbib>0bd9cfef-4cd5-4b20-b953-04ecad0bd71c</tbib> lakes in other settings and with other geometries may not exhibit the same response.
    Many factors influence stream water temperature, including air temperature, forest canopy cover, and ratio of baseflow to streamflow.
- confidence: 'Considering that (a) droughts are projected to intensify in large areas of the Southwest, Great Plains, and the Southeast, and (b) that these same regions have experienced and are projected to experience continuing population and demand increases, confidence that these regions will become increasingly vulnerable to climate change is judged to be high.'
  evidence: |-
    The key message and supporting chapter text summarizes extensive evidence documented in the inter-agency prepared foundational document,<tbib>50d47cc1-5a16-4f5c-bb08-bf6f475a5bb8</tbib> Ch. 2: Our Changing Climate, Ch. 17: Southeast, Ch. 19: Great Plains, Ch. 20: Southwest, Ch. 23: Hawai ‘ i and Pacific Islands, and many technical inputs on a wide range of topics that were received and reviewed as part of the Federal Register Notice solicitation for public input.
    Observed Trends: Historical water withdrawals by sector (for example, municipal, industrial, agricultural, and thermoelectric) have been monitored and documented by USGS for over 40 years and represent a credible database to assess water-use trends, efficiencies, and underlying drivers. Water-use drivers principally include population, personal income, electricity consumption, irrigated area, mean annual temperature, growing season precipitation, and growing season potential evapotranspiration.<tbib>30f46799-40a7-4e54-97f0-841e22aa4a56</tbib> Water-use efficiencies are also affected by many non-climate factors, including demand management, plumbing codes, water efficient appliances, efficiency improvement programs, and pricing strategies;<tbib>c099e537-3373-4ab5-a17b-f6535c694cf3</tbib><sup>,</sup><tbib>77904e24-f8a9-4a0d-b674-64e2510a49fa</tbib><sup>,</sup><tbib>963e9133-8ce2-4d5a-b7e9-2358e99806fc</tbib> changes from water intensive manufacturing and other heavy industrial activities to service-oriented businesses,<tbib>1aeb32af-db3c-4472-a275-356718f12354</tbib> and enhanced water-use efficiencies in response to environmental pollution legislation; replacement of older once-through-cooling electric power plants by plants that recycle their cooling water; and switching from flood irrigation to more efficient methods in the western United States.<tbib>d7f6c804-a121-48cc-9d69-5f9bdf820054</tbib><sup>,</sup><tbib>1d779c76-eb7a-4f43-8853-ecb617638750</tbib>
    Projected Trends and Consequences: Future projections have been carried out with and without climate change to first assess the water demand impacts of projected population and socioeconomic increases, and subsequently combine them with climate change induced impacts. The main findings are that in the absence of climate change total water withdrawals in the U.S. will increase by 3% in the coming 50 years,<tbib>30f46799-40a7-4e54-97f0-841e22aa4a56</tbib> with approximately half of the U.S. experiencing a total water demand decrease and half an increase. If, however, climate change projections are also factored in, the demand for total water withdrawals is projected to rise by an average of 26%,<tbib>30f46799-40a7-4e54-97f0-841e22aa4a56</tbib> with more than 90% of the U.S. projected to experience a total demand increase, and decreases projected only in parts of the Midwest, Northeast, and Southeast. When coupled with the observed and projected drying water cycle trends (see key messages in “Climate Change Impacts on the Water Cycle” section), the water demand impacts of projected population, socioeconomic, and climate changes intensify and compound in the Southwest and Southeast, rendering these regions particularly vulnerable in the coming decades.
  ordinal: 7
  process: ' The chapter author team engaged in multiple technical discussions via teleconferences from March – June 2012. These discussions followed a thorough review of the literature, which included an inter-agency prepared foundational document,<tbib>50d47cc1-5a16-4f5c-bb08-bf6f475a5bb8</tbib> over 500 technical inputs provided by the public, as well as other published literature. The author team met in Seattle, Washington, in May, 2012 for expert deliberation of draft key messages by the authors wherein each message was defended before the entire author team before this key message was selected for inclusion in the Chapter. These discussions were supported by targeted consultation with additional experts by the lead author of each message, and they were based on criteria that help define “key vulnerabilities.” Key messages were further refined following input from the NCADAC report integration team and authors of Ch. 2: Our Changing Climate.'
  statement: 'Climate change affects water demand and the ways water is used within and across regions and economic sectors. The Southwest, Great Plains, and Southeast are particularly vulnerable to changes in water supply and demand.'
  uncertainties: |-
    The studies of water demand in response to climate change and other stressors are very recent and constitute new information on their own merit.<tbib>30f46799-40a7-4e54-97f0-841e22aa4a56</tbib> In addition, for the first time, these studies make it possible to piece together the regional implications of climate change induced water cycle alterations in combination with projected changes in water demand. Such integrated assessments also constitute new information and knowledge building.
    Demand projections include various uncertain assumptions which become increasingly important in longer term (multi-decadal) projections. Because irrigation demand is the largest water demand component most sensitive to climate change, the most important climate related uncertainties are precipitation and potential evapotranspiration over the growing season. Non-climatic uncertainties relate to future population distribution, socioeconomic changes, and water-use efficiency improvements.
- confidence: 'Given the evidence base and remaining uncertainties, confidence is high that changes in precipitation and runoff, combined with changes in consumption and withdrawal, have reduced surface and groundwater supplies in many areas. Confidence is high that these trends are expected to continue, increasing the likelihood of water shortages for many uses.'
  evidence: |-
    The key message and supporting chapter text summarizes extensive evidence documented in the inter-agency prepared foundational document,<tbib>50d47cc1-5a16-4f5c-bb08-bf6f475a5bb8</tbib> Ch. 2: Our Changing Climate, Ch. 17: Southeast, Ch. 19: Great Plains, Ch. 20: Southwest, Ch. 23: Hawai ‘ i and Pacific Islands, and over 500 technical inputs on a wide range of topics that were received and reviewed as part of the Federal Register Notice solicitation for public input.
    Observed Trends: Observations suggest that the water cycle in the Southwest, Great Plains, and Southeast has been changing toward drier conditions (Ch. 17: Southeast).<tbib>d9b704d3-1441-4cf8-a7dc-cc2b1d14c8c5</tbib><sup>,</sup><tbib>9cb51164-e933-48c9-9265-f09b4a9b63a3</tbib><sup>,</sup><tbib>47f6b2ff-a48f-4b48-899d-a901424bf5b2</tbib> Furthermore, paleoclimate tree-ring reconstructions indicate that drought in previous centuries has been more intense and of longer duration than the most extreme drought of the 20 th and 21 st centuries.<tbib>ae89341b-b4bb-4d20-8ebc-20965f751c31</tbib>
    Projected Trends and Consequences: Global Climate Model (GCM) projections indicate that this trend is likely to persist, with runoff reductions (in the range of 10% to 20% over the next 50 years) and intensifying droughts.<tbib>f11e90fb-b100-4487-8bac-1a076166d623</tbib>
    The drying water cycle is expected to affect all human and ecological water uses, especially in the Southwest. Decreasing precipitation, rising temperatures, and drying soils are projected to increase irrigation and outdoor watering demand (which account for nearly 90% of consumptive water use) by as much as 34% by 2060 under the A2 emissions scenario.<tbib>30f46799-40a7-4e54-97f0-841e22aa4a56</tbib> Decreasing runoff and groundwater recharge are expected to reduce surface and groundwater supplies,<tbib>eabfc538-91ce-4130-9040-d595dc61b92e</tbib> increasing the annual risk of water shortages from 25% to 50% by 2060.<tbib>d9b704d3-1441-4cf8-a7dc-cc2b1d14c8c5</tbib> Changes in streamflow timing will increase the mismatch of supply and demand. Earlier and declining streamflow and rising demands will make it more difficult to manage reservoirs, aquifers, and other water infrastructure.<tbib>d9b704d3-1441-4cf8-a7dc-cc2b1d14c8c5</tbib>
    Such impacts and consequences have been identified for several southwestern and western river basins including the Colorado,<tbib>ad8c9969-ccf5-47ef-8f13-2e3c53fb3697</tbib> Rio Grande,<tbib>549a79f8-6a64-46cc-9828-0041dfe2ad54</tbib> and Sacramento-San Joaquin.<tbib>e610dc47-1231-4cbf-b43d-083cc76aa885</tbib><sup>,</sup><tbib>412047fe-33cf-49b8-b714-f1a7b096cd43</tbib><sup>,</sup><tbib>4db2c787-a754-422a-8714-80bbb44def23</tbib>
  ordinal: 8
  process: ' The chapter author team engaged in multiple technical discussions via teleconferences from March – June 2012. These discussions followed a thorough review of the literature, which included an inter-agency prepared foundational document,<tbib>50d47cc1-5a16-4f5c-bb08-bf6f475a5bb8</tbib> over 500 technical inputs provided by the public, as well as other published literature. The author team met in Seattle, Washington, in May, 2012 for expert deliberation of draft key messages by the authors wherein each message was defended before the entire author team before this key message was selected for inclusion in the Chapter. These discussions were supported by targeted consultation with additional experts by the lead author of each message, and they were based on criteria that help define “key vulnerabilities.” Key messages were further refined following input from the NCADAC report integration team and authors of Ch. 2: Our Changing Climate.'
  statement: 'Changes in precipitation and runoff, combined with changes in consumption and withdrawal, have reduced surface and groundwater supplies in many areas. These trends are expected to continue, increasing the likelihood of water shortages for many uses.'
  uncertainties: |-
    The drying climate trend observed in the Southwest and Southeast in the last decades is consistent across all water cycle variables (precipitation, temperature, snow cover, runoff, streamflow, reservoir levels, and soil moisture) and is not debatable. The debate is over whether this trend is part of a multi-decadal climate cycle and whether it will reverse direction at some future time. However, the rate of change and the comparative GCM assessment results with and without historical CO 2 forcing (Ch. 2: Our Changing Climate) support the view that the observed trends are due to both factors acting concurrently.
    GCMs continue to be uncertain with respect to precipitation, but they are very consistent with respect to temperature. Runoff, streamflow, and soil moisture depend on both variables and are thus less susceptible to GCM precipitation uncertainty. The observed trends and the general GCM agreement that the southern states will continue to experience streamflow and soil moisture reductions<tbib>7259bc2b-d0aa-460b-b37a-79a11a386e00</tbib><sup>,</sup><tbib>67b69161-5101-418a-a6c9-1b6a80773305</tbib> provides confidence that these projections are robust.
- confidence: |-
    Future changes in flood frequencies and intensities will depend on a complex combination of local to regional climatic influences and on the details of complex surface-hydrologic conditions in each catchment (for example, topography, land cover, and upstream managements). Consequently, flood frequency changes may be neither simple nor regionally homogeneous, and basin by basin projections may need to be developed. Nonetheless, early results now appearing in the literature have most often projected intensifications of flood regimes, in large part as responses to projections of more intense storms and more rainfall runoff from previously snowbound catchments and settings.
    Therefore confidence is judged to be medium that increasing flooding risk affects human safety and health, property, infrastructure, economies, and ecology in many basins across the U.S.
  evidence: |-
    The key message and supporting chapter text summarizes extensive evidence documented in the inter-agency prepared foundational document,<tbib>50d47cc1-5a16-4f5c-bb08-bf6f475a5bb8</tbib> Ch. 2: Our Changing Climate, Ch. 21: Northwest, Ch. 19: Great Plains, Ch. 18: Midwest, Ch. 16: Northeast, and over 500 technical inputs on a wide range of topics that were received as part of the Federal Register Notice solicitation for public input.
    Observed Trends: Very heavy precipitation events have intensified in recent decades in most U.S. regions, and this trend is projected to continue (Ch. 2: Our Changing Climate). Increasing heavy precipitation is an important contributing factor for floods, but flood magnitude changes also depend on specific watershed conditions (including soil moisture, impervious area, and other human-caused alterations). There is, however, some correspondence among regions with significant changes in annual precipitation (Ch. 2: Our Changing Climate), soil moisture (Figures 3.2 and 3.3), and annual flood magnitudes (Figure 3.5).<tbib>a7f8dbf5-3ec8-4ee1-8740-014006b72bfd</tbib>
    Flooding and seawater intrusion from sea level rise and increasing storm surge threaten New York, Boston, Philadelphia, Virginia Beach, Wilmington, Charleston, Miami, Tampa, Naples, Mobile, Houston, New Orleans, and many other coastal cities (Chapter 25: Coasts).
    Projected Trends: Projections of future flood-frequency changes result from detailed hydrologic<tbib>227f0b59-69f2-47ab-8359-29e4fc383e11</tbib><sup>,</sup><tbib>ffaab9ac-cd7b-47d2-a7df-174dbc479bbb</tbib><sup>,</sup><tbib>37288764-91af-4c74-a5f2-fdf7f088c918</tbib> and hydraulic models of rivers that simulate responses to projected precipitation and temperature changes from climate models.
    Consequences: Floods already affect human health and safety and result in substantial economic, ecological, and infrastructure damages. Many cities are located along coasts and, in some of these cities (including New York, Boston, Miami, Savannah, and New Orleans), sea level rise is expected to exacerbate coastal flooding issues by backing up flood flows and impeding flood-management responses (see Ch. 16: Northeast and Ch. 25: Coasts).<tbib>d0797088-3f92-4cfc-be8d-15027a28378e</tbib>
    Projected changes in flood frequency and severity can bring new challenges in flood risk management. For urban areas in particular, flooding impacts critical infrastructure in ways that are difficult to foresee and can result in interconnected and cascading failures (for example, failure of electrical generating lines can cause pump failure, additional flooding, and failure of evacuation services). Increasing likelihood of flooding also brings with it human health risks associated with failure of critical infrastructure (Ch. 11: Urban)<tbib>2a41e99d-d13e-4b17-b69b-933e4ce5c692</tbib><sup>,</sup><tbib>da7c07ae-84b8-49f6-8911-0e035b9b16cb</tbib><sup>,</sup><tbib>f77ef996-fbed-4d64-887a-ee9525aa84a1</tbib><sup>,</sup><tbib>f8d67434-9bff-4c8d-847e-492b7bf8ee2c</tbib> from waterborne disease that can persist well beyond the occurrence of very heavy precipitation (Ch. 9: Human Health),<tbib>dba82efa-be61-4edd-af85-ee5e3ed07139</tbib> from water outages associated with infrastructure failures that cause decreased sanitary conditions,<tbib>c0f2e34e-88a2-4e63-88ba-408e2efe5162</tbib> and from ecosystem changes that can affect airborne diseases (Ch. 8: Ecosystems).<tbib>05a0fdc2-15ec-44a8-9962-d857c295e281</tbib>
  ordinal: 9
  process: ' The chapter author team engaged in multiple technical discussions via teleconferences from March – June 2012. These discussions followed a thorough review of the literature, which included an inter-agency prepared foundational document,<tbib>50d47cc1-5a16-4f5c-bb08-bf6f475a5bb8</tbib> over 500 technical inputs provided by the public, as well as other published literature. The author team met in Seattle, Washington, in May, 2012 for expert deliberation of draft key messages by the authors wherein each message was defended before the entire author team before this key message was selected for inclusion in the Chapter. These discussions were supported by targeted consultation with additional experts by the lead author of each message, and they were based on criteria that help define “key vulnerabilities.” Key messages were further refined following input from the NCADAC report integration team and authors of Ch. 2: Our Changing Climate.'
  statement: 'Increasing flooding risk affects human safety and health, property, infrastructure, economies, and ecology in many basins across the U.S.'
  uncertainties: 'Large uncertainties still exist as to how well climate models can represent and project future precipitation extremes. However, precipitation extremes are expected to intensify as the atmosphere warms, and many floods result from larger portions of catchment areas receiving rain as snowlines recede upward. As rain runs off more quickly than snowfall, this results in increased flood potential; furthermore occasional rain-on-snow events exacerbates this effect. This trend is broadly expected to increase in frequency under general warming trends, particularly in mountainous catchments.<tbib>73760c11-7b97-4876-a24f-8fb54b01bca9</tbib><sup>,</sup><tbib>fb52dd18-06f2-4774-9262-b00501ff730d</tbib><sup>,</sup><tbib>9417de56-6893-4102-86b7-ad7da4e68b8e</tbib><sup>,</sup><tbib>59b1ce0d-27ed-4224-835a-666a4006d9e8</tbib><sup>,</sup><tbib>7dc6aae5-efaa-489a-807e-8b92e7bcd546</tbib>'
- confidence: |-
    The water resources literature is unanimous that water management should rely less on historical practices and responses and more on robust, risk-based, and adaptive decision approaches.
    Therefore confidence is very high that in most U.S. regions, water resources managers and planners will face new risks, vulnerabilities, and opportunities that may not be properly managed with existing practices.
  evidence: |-
    The key message and supporting chapter text summarizes extensive evidence documented in the inter-agency prepared foundational document,<tbib>50d47cc1-5a16-4f5c-bb08-bf6f475a5bb8</tbib> other chapters of the NCA, and over 500 technical inputs on a wide range of topics that were received as part of the Federal Register Notice solicitation for public input.
    Observed and Projected Trends: Many U.S. regions are facing critical water management and planning challenges. Recent assessments illustrate water management challenges facing California,<tbib>e610dc47-1231-4cbf-b43d-083cc76aa885</tbib><sup>,</sup><tbib>412047fe-33cf-49b8-b714-f1a7b096cd43</tbib><sup>,</sup><tbib>4db2c787-a754-422a-8714-80bbb44def23</tbib><sup>,</sup><tbib>2b2ce56f-645c-4807-9a16-4460433f4861</tbib><sup>,</sup><tbib>32f16a0a-8d25-4e52-9804-1f18632491d6</tbib> the Southwest,<tbib>d9b704d3-1441-4cf8-a7dc-cc2b1d14c8c5</tbib><sup>,</sup><tbib>9cb51164-e933-48c9-9265-f09b4a9b63a3</tbib> Southeast (Ch. 17: Southeast),<tbib>d0797088-3f92-4cfc-be8d-15027a28378e</tbib><sup>,</sup><tbib>47f6b2ff-a48f-4b48-899d-a901424bf5b2</tbib> Northwest,<tbib>c3b1c82e-1821-465f-8466-9d42799340ad</tbib><sup>,</sup><tbib>4babef84-d85e-488e-b8c5-3fb080ebfcd3</tbib><sup>,</sup><tbib>43f67f10-aff3-4d61-8d87-a883adb24771</tbib> Great Plains,<tbib>1e9e830a-b4e4-4a40-8390-5013027453d8</tbib> and Great Lakes.<tbib>125c3ecf-fc2d-46dc-b42b-1d41cfb3ec46</tbib>
    The Sacramento-San Joaquin Bay Delta is already threatened by flooding, seawater intrusion, and changing needs for environmental, municipal, and agricultural water uses. Managing these risks and uses requires re-assessment of a very complex system of water rights, levees, stakeholder consensus processes, reservoir system operations, and significant investments, all of which are subject to large uncertainties.<tbib>7ef83121-d51c-4bc5-b499-e00733fae338</tbib><sup>,</sup><tbib>afffeea6-ab1c-4ffa-9667-5174239693f3</tbib><sup>,</sup><tbib>4acc879e-eae3-4e14-96d5-5e083a548c50</tbib> Given the projected climate changes in the Sacramento-San Joaquin Bay Delta, adherence to historical management and planning practices may not be a long-term viable option,<tbib>412047fe-33cf-49b8-b714-f1a7b096cd43</tbib><sup>,</sup><tbib>4db2c787-a754-422a-8714-80bbb44def23</tbib> but the supporting science is not yet fully actionable,<tbib>c52f2539-9c5e-4ead-b8b7-f1884c5d662e</tbib> and a flexible legal and policy framework embracing change and uncertainty is lacking.
    The Apalachicola-Chattahoochee-Flint (ACF) River basin in Georgia, Alabama, and Florida supports a wide range of water uses and the regional economy, creating challenging water sharing tradeoffs for the basin stakeholders. Climate change presents new stresses and uncertainties.<tbib>47f6b2ff-a48f-4b48-899d-a901424bf5b2</tbib> ACF stakeholders are working to develop a management plan that balances economic, ecological, and social values. <tbib>19d37361-7f68-4f49-a5d9-37d027933146</tbib>
  ordinal: 10
  process: ' The chapter author team engaged in multiple technical discussions via teleconferences from March – June 2012. These discussions followed a thorough review of the literature, which included an inter-agency prepared foundational document,<tbib>50d47cc1-5a16-4f5c-bb08-bf6f475a5bb8</tbib> over 500 technical inputs provided by the public, as well as other published literature. The author team met in Seattle, Washington, in May, 2012 for expert deliberation of draft key messages by the authors wherein each message was defended before the entire author team before this key message was selected for inclusion in the Chapter. These discussions were supported by targeted consultation with additional experts by the lead author of each message, and they were based on criteria that help define “key vulnerabilities.” Key messages were further refined following input from the NCADAC report integration team and authors of Ch. 2: Our Changing Climate.'
  statement: 'In most U.S. regions, water resources managers and planners will encounter new risks, vulnerabilities, and opportunities that may not be properly managed within existing practices.'
  uncertainties: 'Changes in climate, water demand, land use, and demography combine to challenge water management in unprecedented ways. This is happening with a very high degree of certainty in most U.S. regions. Regardless of its underlying causes, climate change poses difficult challenges for water management because it invalidates stationarity – the perception that climate varies around a predictable mean based on the experience of the last century – and increases hydrologic variability and uncertainty. These conditions suggest that past management practices will become increasingly ineffective and that water management can benefit by the adoption of iterative, risk-based, and adaptive approaches.'
- confidence: |-
    Confidence is very high that increasing resilience and enhancing adaptive capacity provide opportunities to strengthen water resources management and plan for climate change impacts.
    Confidence is very high that many institutional, scientific, economic, and political barriers present challenges to implementing adaptive strategies.
  evidence: |-
    The key message and supporting chapter text summarizes extensive evidence documented in the inter-agency prepared foundational document<tbib>50d47cc1-5a16-4f5c-bb08-bf6f475a5bb8</tbib> and over 500 technical inputs on a wide range of topics that were received as part of the Federal Register Notice solicitation for public input.
    There are many examples of adaptive strategies for water infrastructure <tbib>f0803451-5a89-474a-974f-99c13fdc725d</tbib><sup>,</sup><tbib>e0ef030a-67cc-4e80-bc36-0c5b38565145</tbib><sup>,</sup><tbib>6fbd8a7e-0ceb-4f8f-8ebe-5b8598c72ac9</tbib><sup>,</sup><tbib>bc45ac03-924e-4c1e-b681-44e4c1856ca7</tbib> as well as strategies for demand management, land-use and watershed management, and use of “green” infrastructure.<tbib>50d47cc1-5a16-4f5c-bb08-bf6f475a5bb8</tbib><sup>,</sup><tbib>f0803451-5a89-474a-974f-99c13fdc725d</tbib><sup>,</sup><tbib>e0ef030a-67cc-4e80-bc36-0c5b38565145</tbib><sup>,</sup><tbib>01b45a4a-2021-405d-a65b-2340e9ca9677</tbib><sup>,</sup><tbib>cdc46684-79a4-4ea6-ac34-c4abff592f95</tbib>
    Building adaptive capacity ultimately increases the ability to develop and implement adaptation strategies and is considered a no-regrets strategy.<tbib>50d47cc1-5a16-4f5c-bb08-bf6f475a5bb8</tbib><sup>,</sup><tbib>e5126ec0-750d-4efb-b5ca-ccabb47026fc</tbib> Building networks, partnerships, and support systems has been identified as a major asset in building adaptive capacity (Ch. 26: Decision Support; Ch. 28: Adaptation). <tbib>6e2fb7ae-1d84-42c3-b9eb-a215a8c1be86</tbib>
    Water utility associations have undertaken original research to better understand the implications of climate change on behalf of some of the largest municipal water utilities in the United States.<tbib>c2993ef6-7aac-4188-994f-22f85d55738a</tbib><sup>,</sup><tbib>51dc7841-5ccd-4b5f-a5b3-637b8b3fd24f</tbib><sup>,</sup><tbib>6f89df4a-1f6e-4b01-9bf2-9b428ba14013</tbib><sup>,</sup><tbib>f3b4b39d-37b1-417a-979a-11b1ebaff6b7</tbib>
    Challenges include “stationarity” no longer being reliable as the central assumption in water-resource planning <tbib>f488c83c-384f-49d0-b701-cf9ffc858130</tbib>; considerable uncertainties; insufficient actionable science ready for practical application; the challenges of stakeholder engagement; and a lack of agreement on “post-stationarity” paradigms on which to base water laws, regulations, and policies.<tbib>c52f2539-9c5e-4ead-b8b7-f1884c5d662e</tbib> Water administrators may find it necessary to develop more flexible water rights and regulations. <tbib>e0ef030a-67cc-4e80-bc36-0c5b38565145</tbib><sup>,</sup><tbib>3d713826-73c9-44d9-b3a0-45de73e93450</tbib><sup>,</sup><tbib>c95237bc-7d04-4c92-bb83-4a9d8ac3eaed</tbib>
  ordinal: 11
  process: ' The chapter author team engaged in multiple technical discussions via teleconferences from March – June 2012. These discussions followed a thorough review of the literature, which included an inter-agency prepared foundational document,<tbib>50d47cc1-5a16-4f5c-bb08-bf6f475a5bb8</tbib> over 500 technical inputs provided by the public, as well as other published literature. The author team met in Seattle, Washington, in May, 2012 for expert deliberation of draft key messages by the authors wherein each message was defended before the entire author team before this key message was selected for inclusion in the Chapter. These discussions were supported by targeted consultation with additional experts by the lead author of each message, and they were based on criteria that help define “key vulnerabilities.” Key messages were further refined following input from the NCADAC report integration team and authors of Ch. 2: Our Changing Climate.'
  statement: 'Increasing resilience and enhancing adaptive capacity provide opportunities to strengthen water resources management and plan for climate change impacts. Many institutional, scientific, economic, and political barriers present challenges to implementing adaptive strategies.'
  uncertainties: Jurisdictions at the state and local levels are addressing climate change related legal and institutional issues on an individual basis. An ongoing assessment of these efforts may show more practical applications.

